server:
  port: 8086

ribbon:
  eureka:
   enabled: false

# 是否开启熔断器
feignTest:
  ribbon:
    listOfServers: localhost:8082

# 开启日志 格式为logging.level.+Feign客户端路径
logging.level.org.sang.HelloService: debug

# 是否开启熔断器
# feign.hystrix.enabled: true
# 是否开启超时熔断, 如果为false, 则熔断机制只在服务不可用时开启
# hystrix.command.default.execution.timeout.enabled: true
# 设置超时熔断时间
# hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 300




